### ISSUE TITLE
Can the attribute value of the OMAttribute "uri" be a property value ?

### ISSUE THREAD

**Issue by Aifeng1214** [wso2/wso2-synapse#1060]
https://github.com/wso2/wso2-synapse/blob/c0c33dc17fe120907c5aef1458cbafcf3b7b3d24/modules/core/src/main/java/org/apache/synapse/config/xml/endpoints/AddressEndpointFactory.java#L118

I'm new to synapse and I wanna if the rui can be a property's value?
Just like this:
`<property name="callbackUrl" expression="json-eval($.pushUrl)" />
<send> 
    <endpoint> 
         <address uri = "get-property('callbackUrl')" />
    </endpoint> 
</send> 
`
Looking forward for your reply :)

**Comment by isudana** [comment]
Please refer to following blog post.
http://nuwanzone.blogspot.com/2014/01/how-to-send-message-to-dynamic-endpoint.html
