### ISSUE TITLE
Error occurs when having load balancing endpoints with failover

### ISSUE THREAD

**Issue by iloshinik** [wso2/wso2-synapse#1140]
**Description:**
Following error occurs when having load balancing endpoints with failover.

> ERROR {org.apache.synapse.commons.json.JsonUtil} -  #writeAsJson. Payload could not be written as JSON.

**Affected Product Version:**
wso2am-2.0.0

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by isharac** [comment]
Fixed in 37a5da9aa0635929ffeeccbd02bbb0c7f701c27c
