### ISSUE TITLE
PassThroughHttpListener does not shutdown the worker pool threads in the stop method

### ISSUE THREAD

**Issue by nuwanw** [wso2/wso2-synapse#944]
**Description:**
There are four pools initialising in the listener(latencyView, s2sLatencyView, threadingView and worker pool) and those are not shut down when the listener stops. Then the thread are not getting released until JVM shutdown.

Affected Product Version:
wso2-synapse 2.1.7-wso2v25

**Comment by nuwanw** [comment]
Fix https://github.com/wso2/wso2-synapse/pull/943

**Comment by VijithaEkanayake** [comment]
Closing the issue since the fix has been merged.
