### ISSUE TITLE
VFSTransportSender use BinaryFormatter unconditionally..

### ISSUE THREAD

**Issue by dkgkim** [wso2/wso2-synapse#951]
VFSTransportSender use BinaryFormatter unconditionally..

Because below code..

        OMElement firstChild = msgContext.getEnvelope().getBody().getFirstElement();
        if (firstChild != null) {
            if (BaseConstants.DEFAULT_BINARY_WRAPPER.equals(firstChild.getQName())) {
                return new BinaryFormatter();
            } else if (BaseConstants.DEFAULT_TEXT_WRAPPER.equals(firstChild.getQName())) {
                return new PlainTextFormatter();
            }
        }

And..
should not preserve the payload.
because file content size is large to preserve in general.
this value is used in formatter (ex, ExpandingMessageFormatter)
 
       messageFormatter.writeTo(msgContext, format, os, true);

last argument true should be changed to false.

**Comment by VijithaEkanayake** [comment]
@dkgkim 
Could you kindly elaborate use case further to understand the exact issue here?

**Comment by dkgkim** [comment]
when content-type is application/octet-stream and builder is org.wso2.carbon.relay.BinaryRelayBuilder.
And I set the formatter for application/octet-stream to org.wso2.carbon.relay.ExpandingMessageFormatter.

when I send the file to api and api save file to filesystem by vfs sender.

but when I send large file, vfsTransportSender throw Out of memory exception.

because vfs sender use BinaryFormatter and datasource(StreamingOnRequestDataSource) try to store all byte to byte array.

So, I think formatter should be selected by message type and payload should not be preserved.

**Comment by VijithaEkanayake** [comment]
Fixed with https://github.com/wso2/wso2-synapse/pull/952
